<?php
/**
 * @file
 * base_content.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function base_content_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Lagotto Romagnolo',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '007fc5aa-deea-4e1c-8dc8-32a59b2687ae',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Border Collie',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '00d694d9-86f1-462d-a98c-26726f6c6654',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Papillon',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '02242914-8a15-45e0-be6a-ac45b9eec1e7',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Golden Retriever',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '024475ac-6a63-4724-acff-f210d7d1838d',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Whippet',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '033a2087-403c-4995-b01e-62189552764b',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Bearded Collie',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '04e75f15-c02d-405a-a1ae-b3cb548b8bdf',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Beagle',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '067df9a7-5bc5-4357-ba36-8b0e74803207',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Cesky Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '06df50e7-04b5-4248-9178-f6c6389c1f33',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Central Asian Shepherd Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0710047a-5ffc-4ff8-8b11-a0327fe33b6c',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Yorkshire Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0780557a-f2b3-4c14-8e57-4bf8c13d31d4',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Australian Shepherd',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0ad32a77-bf22-4e74-be82-d0998f2bec7c',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Pyrenean Sheepdog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0b5e3c90-b98e-4cee-8f9f-be2842ef2a66',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'German Spitz',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0b7a7c1a-3f79-4e04-a0a7-a1504a7358e3',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Dandie Dinmont Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0dcea74f-569a-4e06-9907-1d928d89e99e',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Puli',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0e1be5c1-52b4-4ee9-8c84-bdf8fb8fbcb1',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Hounds',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '13849232-608e-435a-8c48-5fb78109a71c',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Flat Coated Retriever',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '168e8b47-f5e5-4f57-87d9-bb357ba71f5a',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Manchester Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '16ef1628-7842-49fe-ad3c-a9195b7a16b7',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Chesapeake Bay Retriever',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1745563a-e49f-40fb-8f0c-d8765361e4eb',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Brittany',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1852376f-4d4d-473e-a6f8-eed0de981c1f',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Pug',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1d18c744-44c0-4833-9c4c-a2edfd840852',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Hungarian Wirehaired Vizsla',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1d4f3a0a-4c4b-4b3d-8e12-9f48a5653e2d',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Saluki',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '20cb3b33-780a-420d-a11a-d1614f3f2e5c',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Norfolk Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '222ee688-31c0-4350-94a4-3ff8a2df4e40',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Clumber Spaniel',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '23261882-874a-4bcd-b7cd-a50e626202fb',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Shiba Inu',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2334face-d1f6-40ae-98f4-49e4a3bc055e',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Bernese Mountain Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2477d345-7907-4062-a874-850fc36ce6ad',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'English Toy Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '26f7861c-53ad-4535-bfe9-78c16884ac0a',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Petit Basset',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2c0f1f67-b0a5-4b48-912e-e26a177c84bb',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Belgian Shepherd Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2c328347-69c2-421b-9e44-f4a2560c4c23',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Longhaired Shetland Sheepdog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2cb721a3-1937-4c40-87f1-417beb20d48c',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Azawakh',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2cc590c7-e8ab-41f9-bdfc-048da0411f7b',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Welsh Springer Spaniel',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2cfcfcdc-fb59-4861-8e4d-e3468cca440b',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Dutch Shepherd',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2e67c108-d94f-416a-95de-f71b2d9787ca',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Havanese',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2eb20830-8c3e-48e0-a2e6-18980f20fbc2',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Schipperke',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2f40006a-d685-453c-b033-a715b964912c',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Italian Spinone',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '301d3450-f7fd-4984-a227-4a76d0ccf637',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'German Hunting Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '31eb4716-e90a-4dfa-a95c-4017f0306a4e',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Akita',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '34575eee-9361-46c6-ae4f-e5e9a5fabd8e',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Portuguese Water Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '357da5a9-51cf-4672-a60e-51a8f85ac466',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Samoyed',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '35c028f0-a3c9-45b6-9235-f7eff22e2265',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Great Dane',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '36bc7215-1820-41c6-b1f8-1fd05898995c',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Tatra Shepherd Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '36fb4e9f-bb99-4110-9bc1-d88d05428023',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Greyhound',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '375a4e53-2e63-45e2-bfc4-ab3ab65780aa',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Lowchen',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '37db7b3a-f916-4aee-96a8-a115c4c520ab',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Affenpinscher',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '37f7550f-2a5b-462f-96e6-a406611e56d5',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Cane Corso',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '39120926-6991-4b8f-95e6-12021f955945',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Komondor',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3b69bba4-db57-4fc1-9e39-d77f63267517',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'German Pinscher Leonberger',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3bf0d349-9793-40fa-9824-5ea4814e8bba',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Briard',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3c0a2ca4-765c-4369-a083-9e7f0c065d64',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Large Munsterlander',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3c7954c7-8152-424a-a7b8-892ab2d87afc',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Staffordshire Bull Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3c810d16-99a8-459f-918b-2d25aec85d5c',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Eurasier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3e0be6c3-eb52-4b5b-a2b5-97fe0e2f3c7e',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Irish Red & White Setter',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '3ec23744-7c37-4999-a7ac-8324a5e3acd3',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Welsh Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '40134638-0950-4675-8b3c-a6adef2e8caf',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Fox Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '431f8aea-4d4e-4c93-bee7-0347a95e6ed1',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Curly Coated Retriever',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '44b87732-7571-46ca-82fa-ae4d587084bb',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Irish Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4590c65d-38fc-4260-a48a-f4d1531eafad',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Tibetan Spaniel',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '477eb42e-aa93-48c6-9e88-8ca6b830a46f',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Utility',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Working Dogs',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4b2d0761-2b30-4969-a036-a887abb42566',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Foxhound',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4dffc28f-0216-4870-b6e0-da5d4ae672f9',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Dogue de Bordeaux',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '4ef4ff8b-04ce-4a72-a708-e805e2575e81',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'West Highland White Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '50f40e3b-0f85-4dc2-be33-2c72973abba5',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Hungarian Vizsla',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '528204a7-7b08-4ca0-83db-71523eec5bf0',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Bichon Frise',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '52f6cbf3-911f-47f4-ae08-386dc617e111',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Norwegian Buhund',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5423487c-2016-42bf-87fb-f9596c610dfd',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Sloughi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '56a2add3-3d7d-428e-be07-8f43aaba746a',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Welsh Corgi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5a15055b-6278-42ee-a56a-b704148da94f',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'English Springer Spaniel',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5a191ee8-fd16-4b0d-8eb7-cfce129e3544',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Chinese Crested Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5b03701e-2cee-4cd3-8167-7a9f0fb9240e',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Dalmatian',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5e6b29e7-063a-4609-a3de-69b42ff4166d',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Australian Cattle Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6024800f-8a5e-432a-992c-1deafcb90207',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Cat',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '61179946-2fb7-4d16-b8c8-55c8cd66df5d',
    'vocabulary_machine_name' => 'pet_type',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Basset Hound',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '63b758c6-f1e2-4a44-9f3b-5c761782af2b',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Bergamasco Shepherd Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '65b2ba3f-cec0-4051-a65e-44c0b495c4a9',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Maltese',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6689a4f6-0223-4ce5-94f7-0f52a19dba40',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Harrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '66a1d02b-3f77-4cef-9d5c-f620c9358422',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Scottish Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '67ad6035-0f5b-4876-8d68-cfed1efa06f7',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Peruvian Hairless',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '691dbe0c-51a4-4489-b29f-3bad2f94a4d6',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Australian Stumpy Tail Cattle Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '69ec6796-879e-4d73-aa17-f1c3807103bd',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Boxer',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6e15029e-f70e-45c7-bb21-7a6d31be5279',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Sussex Spaniel Weimaraner',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6e5c6a23-9817-4061-800c-6691b6a28794',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Anatolian Shepherd Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6f782f4b-6fad-453a-9306-eaa34e56536c',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Shar Pei',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '711e4af4-9e7f-4546-a7b1-2c9f55d82755',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Mastiff',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '739c267e-51d9-4f02-a486-95c7301c08de',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Bracco Italiano',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '75af72cb-3657-4556-81a3-8cbf157728e5',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Swedish Vallhund',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7a7e6c49-0dfd-49a2-8de2-9d9491d48171',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Pyrenean Mastiff',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7c451aaf-dc1a-4791-8cc3-1bc56239e62c',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Finnish Spitz',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7d315a30-7c1b-4c27-aa5c-ea6a7ccacfb8',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Gordon Setter',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7fd6f74a-12db-4697-a77f-321849c70917',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Pumi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '80c1b73a-3d9a-480a-ae0d-bcab967f5875',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Dobermann',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8500df38-44be-4119-96ed-8b29a3a1b6c4',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Parson Russell Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8542b74a-8421-460a-a733-535a2ceb2b6a',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Pomeranian',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8740f1a6-5aed-40f4-b460-7b6ce9ac8e42',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Russian Black Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '87852852-b9e9-418d-91fe-1cea2334842e',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Portuguese Podengo',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '88318873-3e2a-4a42-8109-2a0de7aa6329',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Non-Sporting',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '88846542-d763-4c92-a769-12e8553fc115',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Gundogs',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8db213e9-de85-4913-b179-c2b46aea0af1',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Weimaraner',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8ea1dafe-c64c-46e0-a439-2c9431470bee',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'English Setter',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '91291674-daa3-4fd2-894e-215b833a50c2',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Kuvasz',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '91a50c68-e210-4cbe-9997-2e6fd30f362a',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Grand Basset',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9236a669-1c05-477e-921f-4f61d9660cdb',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Spanish Mastiff',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '93a93aaf-8187-4f8a-baba-224acef4d34e',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Boston Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '985141e8-fc5e-4d42-a34b-f278b82b8b3a',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Kerry Blue Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '988f1bb6-b820-42b1-b7b3-8d0321ea508f',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Bloodhound',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '98d3decb-6aab-4f1c-a939-a54f532fbfe2',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Finnish Lapphund',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '99c62528-60af-4e54-9ff3-1dd436b13f63',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Miniature Pinscher',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9b5f09e8-6987-4c14-98f8-4bcd9d38307d',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Hamiltonstovare',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '9e25f227-d4a2-49f5-96ba-87d57e73cf28',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Polish Lowland Sheepdog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a2cd5685-ce9d-4da8-98e5-e8160203c55b',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Bouvier des Flandres',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a471dc92-c85a-421e-b327-93a96ab769d0',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Norwegian Elkhound Otterhound',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a5f191ab-c88e-4c38-82e8-e809e1b1ea26',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Cocker Spaniel',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a62069f0-3766-4a0e-b4db-d9cc0af41e95',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Field Spaniel',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a772ed77-626c-4963-8fc2-decd0e19a0a4',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'King Charles Spaniel',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a85b91a2-d6fe-400a-9b1c-a0e7b4456cf1',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Toys',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Pyrenean Mountain Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'aa67e572-969b-4c3c-92c8-fc08afe45737',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Tibetan Mastiff',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'aa77a424-c3c4-41c5-833a-4d5558c03155',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Chihuahua',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ab3582a9-2947-4a0a-ac2a-f54216123311',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Bluetick Coonhound',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ac19bc94-5611-474a-a5d6-9023239f1fde',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Rhodesian Ridgeback',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'accf3150-9da1-4bd5-b9ad-a71de25b05d1',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Siberian Husky',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ad78720e-1c27-42ce-9585-bb9802901201',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Collie',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'aea8477c-ec85-4af6-ae02-f25f4ceef6b5',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'St. Bernard',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b0dbe558-f82e-438d-9204-440b1000a44f',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Poodle',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b12bb2bf-1ee8-497d-b982-4657255e02d7',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Australian Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b197fae9-222c-4a54-add9-b54b1820ba1b',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'M',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b22a28d7-fb27-43ea-a3d6-bb94b1aeb656',
    'vocabulary_machine_name' => 'pet_sex',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Pointer',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b486bee0-79e3-486c-9059-82f313c8d4c4',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Nova Scotia Duck Tolling Retriever',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b5179e75-3092-4d72-911d-134150bec7b7',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Ibizan Hound',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b6c656d3-d933-4336-873d-32051ddc99fe',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Airedale Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b6f7887a-70d7-4632-a265-63242271323f',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Maremma Sheepdog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b6ff12d5-d7b5-478f-8d87-b355a621f126',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Alaskan Malamute',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b84f8bd0-8e85-428c-a64b-777b28981ebe',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Japanese Spitz',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ba646057-dc42-4f5a-8658-812b6828b28d',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Canaan Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ba7fa64f-5d9d-4a4e-9b32-d12a274713b9',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Old English Sheepdog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bc0c8f51-68fe-4fe3-961a-e3f439daf484',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Australian Kelpie',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bc1796eb-b7f3-4061-bb3c-be04d5d888cd',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Borzoi',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'be7664fc-e36c-403e-b0e3-fa5e0b62662b',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'American Staffordshire Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c30dbfd3-d0db-451e-a371-86fa09045246',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Australian Silky Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c31bf448-2114-46a3-82e7-342f8b95c02e',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Cavalier King Charles Spaniel',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c47d98c8-b88c-490f-9940-923b0ef31249',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Russian Toy',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c545c47c-aaa7-45c7-9922-786397dcb98a',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Bull Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c54c6625-50dd-4ded-80e0-ec46a1b0b976',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'British Bulldog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c7596604-061c-4696-b394-18e99aa2f184',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'German Shepherd Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c89e02ba-8c4b-4cb8-923f-107beacfcf31',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Canadian Eskimo Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd044876b-b5b5-4fa1-8291-865e812f9cd6',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Shih Tzu',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd14662aa-bf40-44d0-bc7d-cf8625b5f9d3',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Cairn Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd1ffa67a-770e-44e8-a7b8-fdc6a0c85f8c',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Labrador Retriever',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd27811b7-514f-4cc0-91c4-8882ea38bf13',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Basenji',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd5acc863-270b-445d-9561-fb766703fe98',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Chow Chow',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd622940a-1785-4dfa-99e6-2e7a8f861e01',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Jack Russell Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd73075b4-a412-4851-8295-cc5bcac3b5eb',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'F',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd75fe5d4-833a-4acb-b505-eb10ba402e3d',
    'vocabulary_machine_name' => 'pet_sex',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Dog',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd9009b6d-8d7b-4ec4-b24d-669461f625a3',
    'vocabulary_machine_name' => 'pet_type',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Tenterfield Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd943cc3b-c3e5-4d4f-b318-df8728395de3',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Keeshond',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd979f53e-d564-4176-b0f9-bc09312c129d',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'French Bulldog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'db442f44-db88-4f39-bed9-2da0b547a4a3',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Italian Greyhound',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dc1b6d69-7444-4276-a9a3-4f4e86834de7',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Sealyham Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dc5d8b4f-cdde-491c-bf11-537bf71db440',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Neapolitan Mastiff Newfoundland',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'dd97fff1-e953-474d-9b6d-37c656572ede',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Japanese Chin',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e033a7db-12ad-4ac0-bbb9-d13cb1187eb8',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Irish Water Spaniel',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e8669026-67c1-4544-aca9-a0953771d3f6',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Rottweiler',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e8ae6760-1e92-4cc5-8a16-c007ba43a7a0',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Dachshund',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e998ab30-0705-4788-94d2-049d1f8d6d44',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Lhasa Apso',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ea89906c-1b54-4e96-8e6c-0c8b97cd1515',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'Swedish Lapphund',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'eb4be99d-ba71-462a-a589-8186ee9508ff',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Terriers',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Bedlington Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ed705ea7-bf35-4c08-903c-29e08d283146',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Irish Setter',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'edd1000e-558a-48c7-9a58-3af536893fdd',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '8db213e9-de85-4913-b179-c2b46aea0af1',
    ),
  );
  $terms[] = array(
    'name' => 'Griffon Vendeen',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'edfe0e2f-3e1e-48b6-9727-04713947f407',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Norwich Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ee0b53de-8fb9-49b1-9659-e9c5121669a7',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Pharaoh Hound',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ee8e5a0f-0a05-4108-aadd-3a85ed81dc71',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Bullmastiff',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f005f848-1c06-4553-bc9e-24b58886849e',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Lakeland Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f064cf0a-3012-4e0e-be28-1481ababd89c',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Afghan Hound',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f1af13aa-9868-4208-84cf-dee18e791522',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Pekingese',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f2dd5a02-4557-4f52-8617-24a5797afe98',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Glen of Imaal Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f335523b-3aaa-4f22-837b-3aeb52600f64',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Tibetan Terrier Xoloitzcuintle',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f38df3c5-ab43-4916-a282-71bab86bf690',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '88846542-d763-4c92-a769-12e8553fc115',
    ),
  );
  $terms[] = array(
    'name' => 'White Swiss Shepherd Dog',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f69b46b5-4b0d-4fea-a767-48d7e577503c',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '4b2d0761-2b30-4969-a036-a887abb42566',
    ),
  );
  $terms[] = array(
    'name' => 'Basset Fauve de Bretagne',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f77c0446-12fb-4290-8e63-464c5a34b377',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Irish Wolfhound',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f88c90b1-3475-4dc3-8d27-a45f2f233a34',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '13849232-608e-435a-8c48-5fb78109a71c',
    ),
  );
  $terms[] = array(
    'name' => 'Skye Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'f9b590c0-6419-45e0-adcd-fca299a4dbaa',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Griffon Bruxellois',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fb343ed5-4904-47be-90c4-784bb0f3d405',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'a9b31315-6eb3-44c3-9c38-002383eaa612',
    ),
  );
  $terms[] = array(
    'name' => 'Schnauzer',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fb3ff8e3-eb7d-4f45-bfb5-741a9b6e8d89',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => '498736e1-11f3-4c85-9d8b-c65fedac1f1e',
    ),
  );
  $terms[] = array(
    'name' => 'Soft Coated Wheaten Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fbb6c7ea-0e4f-476c-a569-32c004a389b4',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  $terms[] = array(
    'name' => 'Border Terrier',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fea0acc7-0261-49ba-8f7c-f1d32001c764',
    'vocabulary_machine_name' => 'pet_breed',
    'metatags' => array(),
    'parent' => array(
      0 => 'ecf33fdc-9d18-4f99-913b-39b0817effe4',
    ),
  );
  return $terms;
}
