<?php

/**
 * Implements hook_menu().
 */
function jpgf_menu()
{
    $items['jpgf/import'] = array(
        'title' => 'Import GF JSON',
        'page callback' => 'jpgf_page',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );

    $items['addimage/%/%'] = array(
        'title' => t("Add your pet's photo"),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('jpgf_aiform', 1, 2),
        'access callback' => 'jpgf_aiaccess',
        'access arguments' => array(1, 2),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function jpgf_aiaccess($nid, $cid)
{
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'pet')
        ->propertyCondition('status', 1)
        ->propertyCondition('nid', $nid)
        ->fieldCondition('field_owner', 'target_id', $cid, '=')
        ->range(0, 1);
    $result = $query->execute();
    if (isset($result['node'])) {
        return TRUE;
    } else {
        return FALSE;
    }
}

function jpgf_aiform($form, &$form_state, $nid, $cid)
{
    $form = array();
    $petNode = node_load($nid);
    $form['#petNode'] = $petNode;

    $form['pet_name'] = array(
        '#markup' => '<p>You are adding an image for ' . $petNode->title . '</p><p>The image on the left is the one you have just uploaded. Drag the dash box to select the area you want to be shown on you certificate and a preview is shown on the right.</p>',
    );


    field_attach_form('node', $petNode, $form, $form_state, NULL, array(
        'field_name' => 'field_pet_image',
    ));

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save'),
        '#weight' => 20,
    );

    return $form;
}

function jpgf_aiform_submit($form, &$form_state)
{
    $petNode = (object)$form['#petNode'];
    $imageField = $form_state['values']['field_pet_image'];

    $petNode->field_pet_image = $imageField;
    entity_save('node', $petNode);

    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'survey_response')
        ->propertyCondition('status', 1)
        ->fieldCondition('field_pet', 'target_id', $petNode->nid, '=')
        ->range(0, 1);
    $result = $query->execute();

    if (isset($result['node'])) {
        $nid = array_keys($result['node']);

        $style = image_style_load('300px_shareable');
        $fid = $petNode->field_pet_image[LANGUAGE_NONE][0]['fid'];
        $file = file_load($fid);
        $source = $file->uri;
       // $destination = "/sites/default/files/public/300px_shareable/";
        $destination = image_style_path($style['name'], $source);
        image_style_create_derivative($style, $source, $destination);

        drupal_goto('node/' . $nid[0]);
    }
}

function jpgf_preprocess_page(&$variables)
{
    drupal_add_js(drupal_get_path('module', 'jpgf') . '/jpgf.js');
}

/**
 * Page example callback, referenced in hook_menu().
 *
 * Description of what the page displays.
 * Second line of the description.
 *
 * @return string
 *   The content of the page.
 */
function jpgf_page()
{
    //This can all go after testing
    $output = process_json();
    variable_set('last_fetch', date(DATE_ATOM));
    //dpm($output);
    return $output;
}

function process_json()
{
    $context = stream_context_create(array(
        'http' => array(
            'method' => "GET",
            'header' => 'Authorization: Bearer 173709a1f841645f8f1a0e0991f37056'
        )
    ));

    $response = file_get_contents('https://api.getfeedback.com/surveys/29880/responses?since=' . urlencode(variable_get('last_fetch')), FALSE, $context);
    // Check for errors
    if ($response === FALSE) {
        // die(curl_error($ch));
    } else {
        // Decode the response
        $responseData = json_decode($response, TRUE);

        $returnData = array();

        foreach ($responseData['active_models'] as $value) {
            if ((!empty($value['answers'])) && ($value['status'] == 'completed')) {
                /*
                create a node object and add to watchdog
                We should check if the id already exists
                 */
                $query = new EntityFieldQuery();
                $query->entityCondition('entity_type', 'node')
                    ->entityCondition('bundle', 'survey_response')
                    ->propertyCondition('status', 1)
                    ->fieldCondition('field_gf_id', 'value', $value['id'], '=')
                    ->range(0, 1)
                    ->addMetaData('account', user_load(1)); // Run the query as user 1.

                $result = $query->execute();

                if (!isset($result['node'])) {

                    // Create the Contact
                    // If the Survey changes, this code will have to change
                    // More of the contact fields need to be added to the GF Survey. Maybe?

                    $cNode = new stdClass(); // We create a new node object
                    $cNode->type = "contact"; // Or any other content type you want
                    $cNode->title = $value['answers'][0]['form_fields'][1]['text'] . " " . $value['answers'][0]['form_fields'][2]['text'];
                    $cNode->language = LANGUAGE_NONE; // Or any language code if Locale module is enabled. More on this below *
                    //$node->path = array('alias' => 'your node path'); // Setting a node path
                    $cNode->field_email[LANGUAGE_NONE][0]['email'] = $value['answers'][0]['form_fields'][4]['text'];
                    node_object_prepare($cNode); // Set some default values.
                    $cNode->uid = 1; // Or any id you wish

                    $cNode = node_submit($cNode); // Prepare node for a submit
                    node_save($cNode); // After this call we'll get a nid
                    watchdog('jpgf', 'New Contact created with ID %nid', array('nid' => $cNode->nid), WATCHDOG_NOTICE);

                    // Create the Pet
                    // If the Survey changes, this code will have to change
                    // More of the pet fields need to be added to the GF Survey. Maybe?

                    $pNode = new stdClass(); // We create a new node object
                    $pNode->type = "pet"; // Or any other content type you want
                    $pNode->title = $value['answers'][0]['form_fields'][0]['text'];
                    $pNode->language = LANGUAGE_NONE; // Or any language code if Locale module is enabled. More on this below *
                    //Could the below be better, using taxonomy to allow for future expansion, but will it?

                    $petSex = '';
                    $petBreed = '';

                    $petSex = taxonomy_get_term_by_name($value['answers'][0]['form_fields'][5]['text'], 'pet_sex');
                    if (!empty($petSex)) {
                        $pNode->field_pet_sex[LANGUAGE_NONE][0]['tid'] = key($petSex);
                    }

                    // TODO: This was to get around field inconsistencies, is it still needed?
                    if ($value['answers'][11]['choices'][0]['text'] == 'Cat') {
                        $petType = taxonomy_get_term_by_name($value['answers'][11]['choices'][0]['text'], 'pet_type');
                    }
                    if ($value['answers'][11]['choices'][0]['text'] == 'Dog') {
                        $petType = taxonomy_get_term_by_name($value['answers'][11]['choices'][0]['text'], 'pet_type');
                    }
                    // TODO: The above will cause warnings at the moment
                    if (!empty($petType)) {
                        $pNode->field_pet_type[LANGUAGE_NONE][0]['tid'] = key($petType);
                    }

                    $query = new EntityFieldQuery();
                    $query->entityCondition('entity_type', 'node')
                        ->entityCondition('bundle', 'pet_character')
                        ->propertyCondition('status', 1)
                        ->propertyOrderBy('title', 'ASC')
                        ->fieldCondition('field_pet_type', 'tid', key($petType))
                        ->fieldCondition('field_pet_sex', 'tid', key($petSex))
                        ->range(0, 10);
                    $result = $query->execute();
                    $nids = array();
                    if (isset($result['node'])) {
                        $nids = array_keys($result['node']);
                    }
                    $characterArray = $nids;

                    //TODO: Is there a better way that's less brittle?
                    $scoreArray = array();
                    $i = 0;
                    foreach ($characterArray as $characterNid => $key) {
                        $scoreArray[$i] = 0;
                        $i++;
                    }

                    $petBreed = taxonomy_get_term_by_name($value['answers'][0]['form_fields'][6]['text'], 'pet_breed');
                    if (!empty($petBreed)) {
                        $breedFamily = taxonomy_get_parents(key($petBreed));
                        $pNode->field_pet_breed[LANGUAGE_NONE][0]['tid'] = key($breedFamily);

                        switch ($breedFamily[key($breedFamily)]->name) {
                            case 'Terriers':
                                //Aristocrat
                                $scoreArray[0] += 24;
                                //Buddy
                                $scoreArray[1] += 30;
                                //Cruiser
                                $scoreArray[2] += 12;
                                //Debonaire
                                $scoreArray[3] += 42;
                                //Defender
                                $scoreArray[4] += 72;
                                //Rough Nut
                                $scoreArray[5] += 72;
                                //Twinkle Toes
                                $scoreArray[6] += 12;
                                //Wanderer
                                $scoreArray[7] += 12;
                                break;
                            case 'Hounds':
                                //Aristocrat
                                $scoreArray[0] += 36;
                                //Buddy
                                $scoreArray[1] += 72;
                                //Cruiser
                                $scoreArray[2] += 54;
                                //Debonaire
                                $scoreArray[3] += 48;
                                //Defender
                                $scoreArray[4] += 12;
                                //Rough Nut
                                $scoreArray[5] += 12;
                                //Twinkle Toes
                                $scoreArray[6] += 12;
                                //Wanderer
                                $scoreArray[7] += 54;
                                break;
                            case 'Non-Sporting':
                                //Aristocrat
                                $scoreArray[0] += 60;
                                //Buddy
                                $scoreArray[1] += 12;
                                //Cruiser
                                $scoreArray[2] += 24;
                                //Debonaire
                                $scoreArray[3] += 0;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 6;
                                //Twinkle Toes
                                $scoreArray[6] += 72;
                                //Wanderer
                                $scoreArray[7] += 6;
                                break;
                            case 'Gundogs':
                                //Aristocrat
                                $scoreArray[0] += 24;
                                //Buddy
                                $scoreArray[1] += 54;
                                //Cruiser
                                $scoreArray[2] += 36;
                                //Debonaire
                                $scoreArray[3] += 54;
                                //Defender
                                $scoreArray[4] += 36;
                                //Rough Nut
                                $scoreArray[5] += 6;
                                //Twinkle Toes
                                $scoreArray[6] += 6;
                                //Wanderer
                                $scoreArray[7] += 42;
                                break;
                            case 'Toys':
                                //Aristocrat
                                $scoreArray[0] += 60;
                                //Buddy
                                $scoreArray[1] += 12;
                                //Cruiser
                                $scoreArray[2] += 12;
                                //Debonaire
                                $scoreArray[3] += 12;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 72;
                                //Wanderer
                                $scoreArray[7] += 24;
                                break;
                            case 'Utility':
                                //Aristocrat
                                $scoreArray[0] += 12;
                                //Buddy
                                $scoreArray[1] += 12;
                                //Cruiser
                                $scoreArray[2] += 54;
                                //Debonaire
                                $scoreArray[3] += 24;
                                //Defender
                                $scoreArray[4] += 42;
                                //Rough Nut
                                $scoreArray[5] += 60;
                                //Twinkle Toes
                                $scoreArray[6] += 0;
                                //Wanderer
                                $scoreArray[7] += 30;
                                break;
                            case 'Working Dogs':
                                //Aristocrat
                                $scoreArray[0] += 24;
                                //Buddy
                                $scoreArray[1] += 12;
                                //Cruiser
                                $scoreArray[2] += 6;
                                //Debonaire
                                $scoreArray[3] += 36;
                                //Defender
                                $scoreArray[4] += 66;
                                //Rough Nut
                                $scoreArray[5] += 72;
                                //Twinkle Toes
                                $scoreArray[6] += 0;
                                //Wanderer
                                $scoreArray[7] += 24;
                                break;
                        }
                    }

                    node_object_prepare($cNode); // Set some default values.
                    $pNode->uid = 1; // Or any id you wish

                    //Create the Survey Response
                    $srNode = new stdClass(); // We create a new node object
                    $srNode->type = "survey_response"; // Or any other content type you want
                    $srNode->title = $value['id'];
                    $srNode->language = LANGUAGE_NONE;

                    node_object_prepare($srNode); // Set some default values.
                    $srNode->uid = 1; // Or any id you wish
                    $srNode->field_gf_id[LANGUAGE_NONE][0]['value'] = $value['id'];
                    $srNode->field_contact[LANGUAGE_NONE][0]['target_id'] = $cNode->nid;

                    // The below seems very brittle, but not sure what else to do right now?
                    //Question 10, what drink? For Dogs
                    if (!empty($value['answers'][1]['choices'][0]['text']) && (key($petType) == 3)) {
                        switch ($value['answers'][1]['choices'][0]['text']) {
                            case 'Fruit Smoothie':
                                //Aristocrat
                                $scoreArray[0] += 7;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 5;
                                //Debonaire
                                $scoreArray[3] += 7;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 7;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Caffiene Hit':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 0;
                                //Cruiser
                                $scoreArray[2] += 0;
                                //Debonaire
                                $scoreArray[3] += 10;
                                //Defender
                                $scoreArray[4] += 10;
                                //Rough Nut
                                $scoreArray[5] += 6;
                                //Twinkle Toes
                                $scoreArray[6] += 7;
                                //Wanderer
                                $scoreArray[7] += 8;
                                break;
                            case 'Fine Wine':
                                //Aristocrat
                                $scoreArray[0] += 10;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 0;
                                //Debonaire
                                $scoreArray[3] += 7;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 2;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Tequila Shot':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 0;
                                //Debonaire
                                $scoreArray[3] += 0;
                                //Defender
                                $scoreArray[4] += 2;
                                //Rough Nut
                                $scoreArray[5] += 7;
                                //Twinkle Toes
                                $scoreArray[6] += 4;
                                //Wanderer
                                $scoreArray[7] += 6;
                                break;
                            case 'Green Tea':
                                //Aristocrat
                                $scoreArray[0] += 4;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 4;
                                //Debonaire
                                $scoreArray[3] += 6;
                                //Defender
                                $scoreArray[4] += 7;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 6;
                                //Wanderer
                                $scoreArray[7] += 3;
                                break;
                            case 'Cold Beer':
                                //Aristocrat
                                $scoreArray[0] += 7;
                                //Buddy
                                $scoreArray[1] += 2;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 0;
                                //Defender
                                $scoreArray[4] += 5;
                                //Rough Nut
                                $scoreArray[5] += 10;
                                //Twinkle Toes
                                $scoreArray[6] += 2;
                                //Wanderer
                                $scoreArray[7] += 7;
                                break;
                        }
                    }

                    //Question 10, what drink? For Cats
                    if (!empty($value['answers'][1]['choices'][0]['text']) && (key($petType) == 4)) {
                        switch ($value['answers'][1]['choices'][0]['text']) {
                            case 'Fruit Smoothie':
                                //Cuddly Cutie
                                $scoreArray[0] += 10;
                                //Timid Kitty
                                $scoreArray[1] += 7;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 6;
                                //Party Animal
                                $scoreArray[4] += 8;
                                //Crazy Cat
                                $scoreArray[5] += 2;
                                break;
                            case 'Caffiene Hit':
                                //Cuddly Cutie
                                $scoreArray[0] += 5;
                                //Timid Kitty
                                $scoreArray[1] += 0;
                                //Fluffy Fun
                                $scoreArray[2] += 0;
                                //Steady Sam
                                $scoreArray[3] += 0;
                                //Party Animal
                                $scoreArray[4] += 7;
                                //Crazy Cat
                                $scoreArray[5] += 10;
                                break;
                            case 'Fine Wine':
                                //Cuddly Cutie
                                $scoreArray[0] += 5;
                                //Timid Kitty
                                $scoreArray[1] += 0;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 3;
                                //Party Animal
                                $scoreArray[4] += 7;
                                //Crazy Cat
                                $scoreArray[5] += 2;
                                break;
                            case 'Tequila Shot':
                                //Cuddly Cutie
                                $scoreArray[0] += 3;
                                //Timid Kitty
                                $scoreArray[1] += 1;
                                //Fluffy Fun
                                $scoreArray[2] += 5;
                                //Steady Sam
                                $scoreArray[3] += 2;
                                //Party Animal
                                $scoreArray[4] += 10;
                                //Crazy Cat
                                $scoreArray[5] += 8;
                                break;
                            case 'Green Tea':
                                //Cuddly Cutie
                                $scoreArray[0] += 4;
                                //Timid Kitty
                                $scoreArray[1] += 10;
                                //Fluffy Fun
                                $scoreArray[2] += 4;
                                //Steady Sam
                                $scoreArray[3] += 5;
                                //Party Animal
                                $scoreArray[4] += 3;
                                //Crazy Cat
                                $scoreArray[5] += 5;
                                break;
                            case 'Cold Beer':
                                //Cuddly Cutie
                                $scoreArray[0] += 3;
                                //Timid Kitty
                                $scoreArray[1] += 1;
                                //Fluffy Fun
                                $scoreArray[2] += 2;
                                //Steady Sam
                                $scoreArray[3] += 10;
                                //Party Animal
                                $scoreArray[4] += 8;
                                //Crazy Cat
                                $scoreArray[5] += 4;
                                break;
                        }
                    }

                    //Question 9, Problem solving For Dogs
                    if (!empty($value['answers'][2]['choices'][0]['text']) && (key($petType) == 3)) {
                        switch ($value['answers'][2]['choices'][0]['text']) {
                            case 'Care & Compromise':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 10;
                                //Cruiser
                                $scoreArray[2] += 6;
                                //Debonaire
                                $scoreArray[3] += 7;
                                //Defender
                                $scoreArray[4] += 6;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Police Identity Kit':
                                //Aristocrat
                                $scoreArray[0] += 5;
                                //Buddy
                                $scoreArray[1] += 0;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 9;
                                //Defender
                                $scoreArray[4] += 9;
                                //Rough Nut
                                $scoreArray[5] += 5;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 1;
                                break;
                            case 'Mathematical Approach':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 2;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 2;
                                //Defender
                                $scoreArray[4] += 10;
                                //Rough Nut
                                $scoreArray[5] += 2;
                                //Twinkle Toes
                                $scoreArray[6] += 8;
                                //Wanderer
                                $scoreArray[7] += 7;
                                break;
                            case 'Outsource - Hired Help':
                                //Aristocrat
                                $scoreArray[0] += 10;
                                //Buddy
                                $scoreArray[1] += 0;
                                //Cruiser
                                $scoreArray[2] += 5;
                                //Debonaire
                                $scoreArray[3] += 5;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 4;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 4;
                                break;
                            case 'Visit a psychic':
                                //Aristocrat
                                $scoreArray[0] += 3;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 2;
                                //Debonaire
                                $scoreArray[3] += 1;
                                //Defender
                                $scoreArray[4] += 4;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 5;
                                //Wanderer
                                $scoreArray[7] += 8;
                                break;
                            case 'Home DIY approach':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 6;
                                //Debonaire
                                $scoreArray[3] += 6;
                                //Defender
                                $scoreArray[4] += 8;
                                //Rough Nut
                                $scoreArray[5] += 7;
                                //Twinkle Toes
                                $scoreArray[6] += 1;
                                //Wanderer
                                $scoreArray[7] += 9;
                                break;
                        }
                    }

                    //Question 9, problem solving For Cats
                    if (!empty($value['answers'][2]['choices'][0]['text']) && (key($petType) == 4)) {
                        switch ($value['answers'][2]['choices'][0]['text']) {
                            case 'Care & Compromise':
                                //Cuddly Cutie
                                $scoreArray[0] += 10;
                                //Timid Kitty
                                $scoreArray[1] += 2;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 5;
                                //Party Animal
                                $scoreArray[4] += 6;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                            case 'Police Identity Kit':
                                //Cuddly Cutie
                                $scoreArray[0] += 4;
                                //Timid Kitty
                                $scoreArray[1] += 10;
                                //Fluffy Fun
                                $scoreArray[2] += 3;
                                //Steady Sam
                                $scoreArray[3] += 2;
                                //Party Animal
                                $scoreArray[4] += 0;
                                //Crazy Cat
                                $scoreArray[5] += 6;
                                break;
                            case 'Mathematical':
                                //Cuddly Cutie
                                $scoreArray[0] += 0;
                                //Timid Kitty
                                $scoreArray[1] += 4;
                                //Fluffy Fun
                                $scoreArray[2] += 6;
                                //Steady Sam
                                $scoreArray[3] += 2;
                                //Party Animal
                                $scoreArray[4] += 0;
                                //Crazy Cat
                                $scoreArray[5] += 8;
                                break;
                            case 'Outsource - Hired Help':
                                //Cuddly Cutie
                                $scoreArray[0] += 3;
                                //Timid Kitty
                                $scoreArray[1] += 4;
                                //Fluffy Fun
                                $scoreArray[2] += 4;
                                //Steady Sam
                                $scoreArray[3] += 2;
                                //Party Animal
                                $scoreArray[4] += 10;
                                //Crazy Cat
                                $scoreArray[5] += 4;
                                break;
                            case 'Visit a psychic':
                                //Cuddly Cutie
                                $scoreArray[0] += 7;
                                //Timid Kitty
                                $scoreArray[1] += 5;
                                //Fluffy Fun
                                $scoreArray[2] += 6;
                                //Steady Sam
                                $scoreArray[3] += 2;
                                //Party Animal
                                $scoreArray[4] += 8;
                                //Crazy Cat
                                $scoreArray[5] += 8;
                                break;
                            case 'Home DIY approach':
                                //Cuddly Cutie
                                $scoreArray[0] += 3;
                                //Timid Kitty
                                $scoreArray[1] += 1;
                                //Fluffy Fun
                                $scoreArray[2] += 3;
                                //Steady Sam
                                $scoreArray[3] += 8;
                                //Party Animal
                                $scoreArray[4] += 3;
                                //Crazy Cat
                                $scoreArray[5] += 3;
                                break;
                        }
                    }

                    //Question 8, Weather For Dogs
                    if (!empty($value['answers'][3]['choices'][0]['text']) && (key($petType) == 3)) {
                        switch ($value['answers'][3]['choices'][0]['text']) {
                            case 'Sunny spring day':
                                //Aristocrat
                                $scoreArray[0] += 6;
                                //Buddy
                                $scoreArray[1] += 8;
                                //Cruiser
                                $scoreArray[2] += 6;
                                //Debonaire
                                $scoreArray[3] += 9;
                                //Defender
                                $scoreArray[4] += 2;
                                //Rough Nut
                                $scoreArray[5] += 3;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 3;
                                break;
                            case 'Foggy, misty & eerie':
                                //Aristocrat
                                $scoreArray[0] += 10;
                                //Buddy
                                $scoreArray[1] += 2;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 1;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 8;
                                //Wanderer
                                $scoreArray[7] += 5;
                                break;
                            case 'Blustery & Windy':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 2;
                                //Cruiser
                                $scoreArray[2] += 0;
                                //Debonaire
                                $scoreArray[3] += 4;
                                //Defender
                                $scoreArray[4] += 10;
                                //Rough Nut
                                $scoreArray[5] += 8;
                                //Twinkle Toes
                                $scoreArray[6] += 4;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Tropics':
                                //Aristocrat
                                $scoreArray[0] += 4;
                                //Buddy
                                $scoreArray[1] += 10;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 6;
                                //Defender
                                $scoreArray[4] += 4;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 0;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Thunder & Lightening':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 6;
                                //Debonaire
                                $scoreArray[3] += 1;
                                //Defender
                                $scoreArray[4] += 9;
                                //Rough Nut
                                $scoreArray[5] += 8;
                                //Twinkle Toes
                                $scoreArray[6] += 6;
                                //Wanderer
                                $scoreArray[7] += 2;
                                break;
                            case 'Blue sky sunset':
                                //Aristocrat
                                $scoreArray[0] += 5;
                                //Buddy
                                $scoreArray[1] += 6;
                                //Cruiser
                                $scoreArray[2] += 4;
                                //Debonaire
                                $scoreArray[3] += 8;
                                //Defender
                                $scoreArray[4] += 2;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 2;
                                //Wanderer
                                $scoreArray[7] += 5;
                                break;
                        }
                    }

                    //Question 8, Weather For Cats
                    if (!empty($value['answers'][3]['choices'][0]['text']) && (key($petType) == 4)) {
                        switch ($value['answers'][3]['choices'][0]['text']) {
                            case 'Sunny spring day':
                                //Cuddly Cutie
                                $scoreArray[0] += 10;
                                //Timid Kitty
                                $scoreArray[1] += 0;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 6;
                                //Party Animal
                                $scoreArray[4] += 10;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                            case 'Foggy, misty & eerie':
                                //Cuddly Cutie
                                $scoreArray[0] += 0;
                                //Timid Kitty
                                $scoreArray[1] += 10;
                                //Fluffy Fun
                                $scoreArray[2] += 0;
                                //Steady Sam
                                $scoreArray[3] += 0;
                                //Party Animal
                                $scoreArray[4] += 0;
                                //Crazy Cat
                                $scoreArray[5] += 9;
                                break;
                            case 'Blustery & Windy':
                                //Cuddly Cutie
                                $scoreArray[0] += 0;
                                //Timid Kitty
                                $scoreArray[1] += 6;
                                //Fluffy Fun
                                $scoreArray[2] += 0;
                                //Steady Sam
                                $scoreArray[3] += 0;
                                //Party Animal
                                $scoreArray[4] += 4;
                                //Crazy Cat
                                $scoreArray[5] += 9;
                                break;
                            case 'Tropics':
                                //Cuddly Cutie
                                $scoreArray[0] += 5;
                                //Timid Kitty
                                $scoreArray[1] += 2;
                                //Fluffy Fun
                                $scoreArray[2] += 6;
                                //Steady Sam
                                $scoreArray[3] += 4;
                                //Party Animal
                                $scoreArray[4] += 10;
                                //Crazy Cat
                                $scoreArray[5] += 4;
                                break;
                            case 'Thunder & Lightening':
                                //Cuddly Cutie
                                $scoreArray[0] += 0;
                                //Timid Kitty
                                $scoreArray[1] += 7;
                                //Fluffy Fun
                                $scoreArray[2] += 0;
                                //Steady Sam
                                $scoreArray[3] += 0;
                                //Party Animal
                                $scoreArray[4] += 4;
                                //Crazy Cat
                                $scoreArray[5] += 10;
                                break;
                            case 'Pink-orange sunset':
                                //Cuddly Cutie
                                $scoreArray[0] += 10;
                                //Timid Kitty
                                $scoreArray[1] += 1;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 5;
                                //Party Animal
                                $scoreArray[4] += 9;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                        }
                    }

                    //Question 7, Where to live For Dogs
                    if (!empty($value['answers'][4]['choices'][0]['text']) && (key($petType) == 3)) {
                        switch ($value['answers'][4]['choices'][0]['text']) {
                            case 'Big house with security':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 0;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 4;
                                //Defender
                                $scoreArray[4] += 8;
                                //Rough Nut
                                $scoreArray[5] += 10;
                                //Twinkle Toes
                                $scoreArray[6] += 5;
                                //Wanderer
                                $scoreArray[7] += 5;
                                break;
                            case 'Island resort':
                                //Aristocrat
                                $scoreArray[0] += 5;
                                //Buddy
                                $scoreArray[1] += 6;
                                //Cruiser
                                $scoreArray[2] += 4;
                                //Debonaire
                                $scoreArray[3] += 8;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 2;
                                //Twinkle Toes
                                $scoreArray[6] += 2;
                                //Wanderer
                                $scoreArray[7] += 2;
                                break;
                            case 'Shed':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 5;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 0;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 6;
                                //Twinkle Toes
                                $scoreArray[6] += 7;
                                //Wanderer
                                $scoreArray[7] += 8;
                                break;
                            case 'Modern apartment':
                                //Aristocrat
                                $scoreArray[0] += 10;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 8;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 4;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Wooden cabin in nature':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 10;
                                //Cruiser
                                $scoreArray[2] += 4;
                                //Debonaire
                                $scoreArray[3] += 7;
                                //Defender
                                $scoreArray[4] += 7;
                                //Rough Nut
                                $scoreArray[5] += 3;
                                //Twinkle Toes
                                $scoreArray[6] += 4;
                                //Wanderer
                                $scoreArray[7] += 5;
                                break;
                            case 'Motorhome':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 5;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 5;
                                //Defender
                                $scoreArray[4] += 2;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 10;
                                break;
                        }
                    }

                    //Question 7, Home For Cats
                    if (!empty($value['answers'][4]['choices'][0]['text']) && (key($petType) == 4)) {
                        switch ($value['answers'][4]['choices'][0]['text']) {
                            case 'Romantic hideaway':
                                //Cuddly Cutie
                                $scoreArray[0] += 10;
                                //Timid Kitty
                                $scoreArray[1] += 5;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 3;
                                //Party Animal
                                $scoreArray[4] += 8;
                                //Crazy Cat
                                $scoreArray[5] += 3;
                                break;
                            case 'Motorhome':
                                //Cuddly Cutie
                                $scoreArray[0] += 5;
                                //Timid Kitty
                                $scoreArray[1] += 10;
                                //Fluffy Fun
                                $scoreArray[2] += 5;
                                //Steady Sam
                                $scoreArray[3] += 6;
                                //Party Animal
                                $scoreArray[4] += 3;
                                //Crazy Cat
                                $scoreArray[5] += 3;
                                break;
                            case 'Modern Apartment':
                                //Cuddly Cutie
                                $scoreArray[0] += 5;
                                //Timid Kitty
                                $scoreArray[1] += 2;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 4;
                                //Party Animal
                                $scoreArray[4] += 10;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                            case 'Island Resort':
                                //Cuddly Cutie
                                $scoreArray[0] += 7;
                                //Timid Kitty
                                $scoreArray[1] += 1;
                                //Fluffy Fun
                                $scoreArray[2] += 6;
                                //Steady Sam
                                $scoreArray[3] += 4;
                                //Party Animal
                                $scoreArray[4] += 10;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                            case 'Natural History Museum':
                                //Cuddly Cutie
                                $scoreArray[0] += 1;
                                //Timid Kitty
                                $scoreArray[1] += 6;
                                //Fluffy Fun
                                $scoreArray[2] += 4;
                                //Steady Sam
                                $scoreArray[3] += 3;
                                //Party Animal
                                $scoreArray[4] += 0;
                                //Crazy Cat
                                $scoreArray[5] += 10;
                                break;
                            case 'Castle with servants':
                                //Cuddly Cutie
                                $scoreArray[0] += 6;
                                //Timid Kitty
                                $scoreArray[1] += 7;
                                //Fluffy Fun
                                $scoreArray[2] += 3;
                                //Steady Sam
                                $scoreArray[3] += 7;
                                //Party Animal
                                $scoreArray[4] += 5;
                                //Crazy Cat
                                $scoreArray[5] += 6;
                                break;
                        }
                    }

                    //Question 6, Vehicle For Dogs
                    if (!empty($value['answers'][5]['choices'][0]['text']) && (key($petType) == 3)) {
                        switch ($value['answers'][5]['choices'][0]['text']) {
                            case 'VW Convertable':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 4;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 7;
                                //Defender
                                $scoreArray[4] += 3;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 5;
                                //Wanderer
                                $scoreArray[7] += 2;
                                break;
                            case 'Harley Davidson':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 2;
                                //Cruiser
                                $scoreArray[2] += 0;
                                //Debonaire
                                $scoreArray[3] += 6;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 9;
                                //Twinkle Toes
                                $scoreArray[6] += 2;
                                //Wanderer
                                $scoreArray[7] += 3;
                                break;
                            case 'Smart Car':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 5;
                                //Cruiser
                                $scoreArray[2] += 4;
                                //Debonaire
                                $scoreArray[3] += 0;
                                //Defender
                                $scoreArray[4] += 10;
                                //Rough Nut
                                $scoreArray[5] += 2;
                                //Twinkle Toes
                                $scoreArray[6] += 4;
                                //Wanderer
                                $scoreArray[7] += 5;
                                break;
                            case 'Limosine':
                                //Aristocrat
                                $scoreArray[0] += 10;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 0;
                                //Debonaire
                                $scoreArray[3] += 9;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 2;
                                //Twinkle Toes
                                $scoreArray[6] += 0;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Icecream Van':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 7;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 1;
                                //Defender
                                $scoreArray[4] += 2;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 6;
                                //Wanderer
                                $scoreArray[7] += 2;
                                break;
                            case 'Vintage Cadilac':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 4;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 6;
                                //Defender
                                $scoreArray[4] += 3;
                                //Rough Nut
                                $scoreArray[5] += 7;
                                //Twinkle Toes
                                $scoreArray[6] += 5;
                                //Wanderer
                                $scoreArray[7] += 2;
                                break;
                        }
                    }

                    //Question 6, Vehicle For Cats
                    if (!empty($value['answers'][5]['choices'][0]['text']) && (key($petType) == 4)) {
                        switch ($value['answers'][5]['choices'][0]['text']) {
                            case 'VW Convertible':
                                //Cuddly Cutie
                                $scoreArray[0] += 10;
                                //Timid Kitty
                                $scoreArray[1] += 0;
                                //Fluffy Fun
                                $scoreArray[2] += 5;
                                //Steady Sam
                                $scoreArray[3] += 3;
                                //Party Animal
                                $scoreArray[4] += 4;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                            case 'Harley Davidson Motorcycle with Sidecar':
                                //Cuddly Cutie
                                $scoreArray[0] += 2;
                                //Timid Kitty
                                $scoreArray[1] += 0;
                                //Fluffy Fun
                                $scoreArray[2] += 3;
                                //Steady Sam
                                $scoreArray[3] += 3;
                                //Party Animal
                                $scoreArray[4] += 6;
                                //Crazy Cat
                                $scoreArray[5] += 6;
                                break;
                            case 'Volvo Station Wagon':
                                //Cuddly Cutie
                                $scoreArray[0] += 2;
                                //Timid Kitty
                                $scoreArray[1] += 9;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 7;
                                //Party Animal
                                $scoreArray[4] += 0;
                                //Crazy Cat
                                $scoreArray[5] += 2;
                                break;
                            case 'Limo':
                                //Cuddly Cutie
                                $scoreArray[0] += 5;
                                //Timid Kitty
                                $scoreArray[1] += 0;
                                //Fluffy Fun
                                $scoreArray[2] += 3;
                                //Steady Sam
                                $scoreArray[3] += 2;
                                //Party Animal
                                $scoreArray[4] += 10;
                                //Crazy Cat
                                $scoreArray[5] += 2;
                                break;
                            case 'Icecream Van':
                                //Cuddly Cutie
                                $scoreArray[0] += 4;
                                //Timid Kitty
                                $scoreArray[1] += 0;
                                //Fluffy Fun
                                $scoreArray[2] += 3;
                                //Steady Sam
                                $scoreArray[3] += 4;
                                //Party Animal
                                $scoreArray[4] += 6;
                                //Crazy Cat
                                $scoreArray[5] += 10;
                                break;
                            case 'Dune Buggy':
                                //Cuddly Cutie
                                $scoreArray[0] += 2;
                                //Timid Kitty
                                $scoreArray[1] += 0;
                                //Fluffy Fun
                                $scoreArray[2] += 3;
                                //Steady Sam
                                $scoreArray[3] += 3;
                                //Party Animal
                                $scoreArray[4] += 10;
                                //Crazy Cat
                                $scoreArray[5] += 4;
                                break;
                        }
                    }

                    //Question 5, What costume For Dogs
                    if (!empty($value['answers'][6]['choices'][0]['text']) && (key($petType) == 3)) {
                        switch ($value['answers'][6]['choices'][0]['text']) {
                            case 'Fluffy Rabbit':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 2;
                                //Debonaire
                                $scoreArray[3] += 1;
                                //Defender
                                $scoreArray[4] += 6;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 4;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Ninja':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 2;
                                //Cruiser
                                $scoreArray[2] += 2;
                                //Debonaire
                                $scoreArray[3] += 7;
                                //Defender
                                $scoreArray[4] += 3;
                                //Rough Nut
                                $scoreArray[5] += 10;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 10;
                                break;
                            case 'Superhero':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 7;
                                //Cruiser
                                $scoreArray[2] += 4;
                                //Debonaire
                                $scoreArray[3] += 10;
                                //Defender
                                $scoreArray[4] += 5;
                                //Rough Nut
                                $scoreArray[5] += 9;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 5;
                                break;
                            case 'Disco diva':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 2;
                                //Cruiser
                                $scoreArray[2] += 2;
                                //Debonaire
                                $scoreArray[3] += 6;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 0;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Doctor or Nurse':
                                //Aristocrat
                                $scoreArray[0] += 10;
                                //Buddy
                                $scoreArray[1] += 5;
                                //Cruiser
                                $scoreArray[2] += 2;
                                //Debonaire
                                $scoreArray[3] += 7;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 4;
                                //Twinkle Toes
                                $scoreArray[6] += 2;
                                //Wanderer
                                $scoreArray[7] += 4;
                                break;
                            case 'Crazy Monster':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 5;
                                //Cruiser
                                $scoreArray[2] += 4;
                                //Debonaire
                                $scoreArray[3] += 1;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 8;
                                //Twinkle Toes
                                $scoreArray[6] += 7;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                        }
                    }

                    //Question 5, Costume For Cats
                    if (!empty($value['answers'][6]['choices'][0]['text']) && (key($petType) == 4)) {
                        switch ($value['answers'][6]['choices'][0]['text']) {
                            case 'Fluffy Rabbit':
                                //Cuddly Cutie
                                $scoreArray[0] += 10;
                                //Timid Kitty
                                $scoreArray[1] += 1;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 0;
                                //Party Animal
                                $scoreArray[4] += 10;
                                //Crazy Cat
                                $scoreArray[5] += 3;
                                break;
                            case 'Ninja':
                                //Cuddly Cutie
                                $scoreArray[0] += 0;
                                //Timid Kitty
                                $scoreArray[1] += 10;
                                //Fluffy Fun
                                $scoreArray[2] += 0;
                                //Steady Sam
                                $scoreArray[3] += 2;
                                //Party Animal
                                $scoreArray[4] += 7;
                                //Crazy Cat
                                $scoreArray[5] += 8;
                                break;
                            case 'Doctor or Nurse':
                                //Cuddly Cutie
                                $scoreArray[0] += 6;
                                //Timid Kitty
                                $scoreArray[1] += 2;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 6;
                                //Party Animal
                                $scoreArray[4] += 7;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                            case 'Disco Diva':
                                //Cuddly Cutie
                                $scoreArray[0] += 7;
                                //Timid Kitty
                                $scoreArray[1] += 2;
                                //Fluffy Fun
                                $scoreArray[2] += 5;
                                //Steady Sam
                                $scoreArray[3] += 3;
                                //Party Animal
                                $scoreArray[4] += 10;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                            case 'Groucho Marx':
                                //Cuddly Cutie
                                $scoreArray[0] += 0;
                                //Timid Kitty
                                $scoreArray[1] += 10;
                                //Fluffy Fun
                                $scoreArray[2] += 4;
                                //Steady Sam
                                $scoreArray[3] += 0;
                                //Party Animal
                                $scoreArray[4] += 5;
                                //Crazy Cat
                                $scoreArray[5] += 10;
                                break;
                            case 'Superhero':
                                //Cuddly Cutie
                                $scoreArray[0] += 2;
                                //Timid Kitty
                                $scoreArray[1] += 2;
                                //Fluffy Fun
                                $scoreArray[2] += 0;
                                //Steady Sam
                                $scoreArray[3] += 6;
                                //Party Animal
                                $scoreArray[4] += 7;
                                //Crazy Cat
                                $scoreArray[5] += 5;
                                break;
                        }
                    }

                    //Question 4, What Movie For Dogs
                    if (!empty($value['answers'][7]['choices'][0]['text']) && (key($petType) == 3)) {
                        switch ($value['answers'][7]['choices'][0]['text']) {
                            case 'Adventure':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 5;
                                //Cruiser
                                $scoreArray[2] += 4;
                                //Debonaire
                                $scoreArray[3] += 6;
                                //Defender
                                $scoreArray[4] += 6;
                                //Rough Nut
                                $scoreArray[5] += 10;
                                //Twinkle Toes
                                $scoreArray[6] += 2;
                                //Wanderer
                                $scoreArray[7] += 7;
                                break;
                            case 'Chick flick':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 9;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 4;
                                //Wanderer
                                $scoreArray[7] += 1;
                                break;
                            case 'Documentary':
                                //Aristocrat
                                $scoreArray[0] += 6;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 4;
                                //Defender
                                $scoreArray[4] += 1;
                                //Rough Nut
                                $scoreArray[5] += 5;
                                //Twinkle Toes
                                $scoreArray[6] += 7;
                                //Wanderer
                                $scoreArray[7] += 10;
                                break;
                            case 'Horror':
                                //Aristocrat
                                $scoreArray[0] += 7;
                                //Buddy
                                $scoreArray[1] += 0;
                                //Cruiser
                                $scoreArray[2] += 0;
                                //Debonaire
                                $scoreArray[3] += 1;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 10;
                                //Twinkle Toes
                                $scoreArray[6] += 5;
                                //Wanderer
                                $scoreArray[7] += 7;
                                break;
                            case 'Sci Fi':
                                //Aristocrat
                                $scoreArray[0] += 2;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 6;
                                //Debonaire
                                $scoreArray[3] += 6;
                                //Defender
                                $scoreArray[4] += 6;
                                //Rough Nut
                                $scoreArray[5] += 5;
                                //Twinkle Toes
                                $scoreArray[6] += 10;
                                //Wanderer
                                $scoreArray[7] += 3;
                                break;
                            case 'Comedy':
                                //Aristocrat
                                $scoreArray[0] += 1;
                                //Buddy
                                $scoreArray[1] += 10;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 5;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 1;
                                //Twinkle Toes
                                $scoreArray[6] += 1;
                                //Wanderer
                                $scoreArray[7] += 2;
                                break;
                        }
                    }

                    //Question 4, Movie For Cats
                    if (!empty($value['answers'][7]['choices'][0]['text']) && (key($petType) == 4)) {
                        switch ($value['answers'][7]['choices'][0]['text']) {
                            case 'Romance':
                                //Cuddly Cutie
                                $scoreArray[0] += 10;
                                //Timid Kitty
                                $scoreArray[1] += 3;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 4;
                                //Party Animal
                                $scoreArray[4] += 8;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                            case 'Horror':
                                //Cuddly Cutie
                                $scoreArray[0] += 0;
                                //Timid Kitty
                                $scoreArray[1] += 7;
                                //Fluffy Fun
                                $scoreArray[2] += 0;
                                //Steady Sam
                                $scoreArray[3] += 2;
                                //Party Animal
                                $scoreArray[4] += 4;
                                //Crazy Cat
                                $scoreArray[5] += 10;
                                break;
                            case 'Action':
                                //Cuddly Cutie
                                $scoreArray[0] += 4;
                                //Timid Kitty
                                $scoreArray[1] += 6;
                                //Fluffy Fun
                                $scoreArray[2] += 5;
                                //Steady Sam
                                $scoreArray[3] += 2;
                                //Party Animal
                                $scoreArray[4] += 6;
                                //Crazy Cat
                                $scoreArray[5] += 8;
                                break;
                            case 'Documentary':
                                //Cuddly Cutie
                                $scoreArray[0] += 5;
                                //Timid Kitty
                                $scoreArray[1] += 6;
                                //Fluffy Fun
                                $scoreArray[2] += 4;
                                //Steady Sam
                                $scoreArray[3] += 6;
                                //Party Animal
                                $scoreArray[4] += 4;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                            case 'Sci-Fi':
                                //Cuddly Cutie
                                $scoreArray[0] += 0;
                                //Timid Kitty
                                $scoreArray[1] += 7;
                                //Fluffy Fun
                                $scoreArray[2] += 2;
                                //Steady Sam
                                $scoreArray[3] += 3;
                                //Party Animal
                                $scoreArray[4] += 5;
                                //Crazy Cat
                                $scoreArray[5] += 7;
                                break;
                            case 'Comedy':
                                //Cuddly Cutie
                                $scoreArray[0] += 8;
                                //Timid Kitty
                                $scoreArray[1] += 1;
                                //Fluffy Fun
                                $scoreArray[2] += 6;
                                //Steady Sam
                                $scoreArray[3] += 7;
                                //Party Animal
                                $scoreArray[4] += 10;
                                //Crazy Cat
                                $scoreArray[5] += 4;
                                break;
                        }
                    }

                    //Question 3, What Meal For Dogs.
                    if (!empty($value['answers'][8]['choices'][0]['text']) && (key($petType) == 3)) {
                        switch ($value['answers'][8]['choices'][0]['text']) {
                            case 'Fish & Chips':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 7;
                                //Cruiser
                                $scoreArray[2] += 5;
                                //Debonaire
                                $scoreArray[3] += 2;
                                //Defender
                                $scoreArray[4] += 5;
                                //Rough Nut
                                $scoreArray[5] += 8;
                                //Twinkle Toes
                                $scoreArray[6] += 4;
                                //Wanderer
                                $scoreArray[7] += 10;
                                break;
                            case 'Healthy treats':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 4;
                                //Cruiser
                                $scoreArray[2] += 5;
                                //Debonaire
                                $scoreArray[3] += 2;
                                //Defender
                                $scoreArray[4] += 5;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Gourmet picnic hamper':
                                //Aristocrat
                                $scoreArray[0] += 10;
                                //Buddy
                                $scoreArray[1] += 7;
                                //Cruiser
                                $scoreArray[2] += 4;
                                //Debonaire
                                $scoreArray[3] += 9;
                                //Defender
                                $scoreArray[4] += 2;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 2;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Sunday Roast':
                                //Aristocrat
                                $scoreArray[0] += 5;
                                //Buddy
                                $scoreArray[1] += 4;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 5;
                                //Defender
                                $scoreArray[4] += 10;
                                //Rough Nut
                                $scoreArray[5] += 5;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 6;
                                break;
                            case 'Candlelit Dinner':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 7;
                                //Cruiser
                                $scoreArray[2] += 3;
                                //Debonaire
                                $scoreArray[3] += 10;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 2;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Finger food':
                                //Aristocrat
                                $scoreArray[0] += 1;
                                //Buddy
                                $scoreArray[1] += 6;
                                //Cruiser
                                $scoreArray[2] += 5;
                                //Debonaire
                                $scoreArray[3] += 1;
                                //Defender
                                $scoreArray[4] += 6;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 6;
                                //Wanderer
                                $scoreArray[7] += 3;
                                break;
                        }
                    }

                    //Question 3, Meal For Cats
                    if (!empty($value['answers'][8]['choices'][0]['text']) && (key($petType) == 4)) {
                        switch ($value['answers'][8]['choices'][0]['text']) {
                            case 'Candlelit dinner':
                                //Cuddly Cutie
                                $scoreArray[0] += 10;
                                //Timid Kitty
                                $scoreArray[1] += 1;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 4;
                                //Party Animal
                                $scoreArray[4] += 7;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                            case 'Healthy treats':
                                //Cuddly Cutie
                                $scoreArray[0] += 7;
                                //Timid Kitty
                                $scoreArray[1] += 3;
                                //Fluffy Fun
                                $scoreArray[2] += 6;
                                //Steady Sam
                                $scoreArray[3] += 4;
                                //Party Animal
                                $scoreArray[4] += 5;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                            case 'Gourmet Picnic Hamper':
                                //Cuddly Cutie
                                $scoreArray[0] += 8;
                                //Timid Kitty
                                $scoreArray[1] += 2;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 4;
                                //Party Animal
                                $scoreArray[4] += 8;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                            case 'Finger food, fairy bread':
                                //Cuddly Cutie
                                $scoreArray[0] += 8;
                                //Timid Kitty
                                $scoreArray[1] += 1;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 4;
                                //Party Animal
                                $scoreArray[4] += 10;
                                //Crazy Cat
                                $scoreArray[5] += 3;
                                break;
                            case 'Candy coated birds & mice':
                                //Cuddly Cutie
                                $scoreArray[0] += 8;
                                //Timid Kitty
                                $scoreArray[1] += 4;
                                //Fluffy Fun
                                $scoreArray[2] += 4;
                                //Steady Sam
                                $scoreArray[3] += 3;
                                //Party Animal
                                $scoreArray[4] += 4;
                                //Crazy Cat
                                $scoreArray[5] += 10;
                                break;
                            case 'Baked beans on toast (if youre lucky)':
                                //Cuddly Cutie
                                $scoreArray[0] += 3;
                                //Timid Kitty
                                $scoreArray[1] += 6;
                                //Fluffy Fun
                                $scoreArray[2] += 2;
                                //Steady Sam
                                $scoreArray[3] += 10;
                                //Party Animal
                                $scoreArray[4] += 2;
                                //Crazy Cat
                                $scoreArray[5] += 3;
                                break;
                        }
                    }

                    //Question 2, What Recreation For Dogs
                    if (!empty($value['answers'][9]['choices'][0]['text']) && (key($petType) == 3)) {
                        switch ($value['answers'][9]['choices'][0]['text']) {
                            case 'Fly fishing':
                                //Aristocrat
                                $scoreArray[0] += 5;
                                //Buddy
                                $scoreArray[1] += 0;
                                //Cruiser
                                $scoreArray[2] += 5;
                                //Debonaire
                                $scoreArray[3] += 6;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 10;
                                break;
                            case 'Modern Dance':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 5;
                                //Cruiser
                                $scoreArray[2] += 4;
                                //Debonaire
                                $scoreArray[3] += 2;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 5;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Boxing':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 0;
                                //Cruiser
                                $scoreArray[2] += 0;
                                //Debonaire
                                $scoreArray[3] += 7;
                                //Defender
                                $scoreArray[4] += 5;
                                //Rough Nut
                                $scoreArray[5] += 10;
                                //Twinkle Toes
                                $scoreArray[6] += 0;
                                //Wanderer
                                $scoreArray[7] += 4;
                                break;
                            case 'Tennis':
                                //Aristocrat
                                $scoreArray[0] += 5;
                                //Buddy
                                $scoreArray[1] += 10;
                                //Cruiser
                                $scoreArray[2] += 5;
                                //Debonaire
                                $scoreArray[3] += 6;
                                //Defender
                                $scoreArray[4] += 5;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 0;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Pole vaulting':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 0;
                                //Cruiser
                                $scoreArray[2] += 0;
                                //Debonaire
                                $scoreArray[3] += 5;
                                //Defender
                                $scoreArray[4] += 7;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 2;
                                //Wanderer
                                $scoreArray[7] += 5;
                                break;
                            case 'Chess':
                                //Aristocrat
                                $scoreArray[0] += 10;
                                //Buddy
                                $scoreArray[1] += 4;
                                //Cruiser
                                $scoreArray[2] += 5;
                                //Debonaire
                                $scoreArray[3] += 7;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 3;
                                //Twinkle Toes
                                $scoreArray[6] += 7;
                                //Wanderer
                                $scoreArray[7] += 6;
                                break;
                        }
                    }

                    //Question 2, Recreation For Cats
                    if (!empty($value['answers'][9]['choices'][0]['text']) && (key($petType) == 4)) {
                        switch ($value['answers'][9]['choices'][0]['text']) {
                            case 'Ballroom dancing':
                                //Cuddly Cutie
                                $scoreArray[0] += 8;
                                //Timid Kitty
                                $scoreArray[1] += 2;
                                //Fluffy Fun
                                $scoreArray[2] += 6;
                                //Steady Sam
                                $scoreArray[3] += 2;
                                //Party Animal
                                $scoreArray[4] += 9;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                            case 'Wide-mouth clown Carnival games':
                                //Cuddly Cutie
                                $scoreArray[0] += 4;
                                //Timid Kitty
                                $scoreArray[1] += 6;
                                //Fluffy Fun
                                $scoreArray[2] += 6;
                                //Steady Sam
                                $scoreArray[3] += 4;
                                //Party Animal
                                $scoreArray[4] += 5;
                                //Crazy Cat
                                $scoreArray[5] += 10;
                                break;
                            case 'Pole vaulting':
                                //Cuddly Cutie
                                $scoreArray[0] += 0;
                                //Timid Kitty
                                $scoreArray[1] += 3;
                                //Fluffy Fun
                                $scoreArray[2] += 6;
                                //Steady Sam
                                $scoreArray[3] += 3;
                                //Party Animal
                                $scoreArray[4] += 8;
                                //Crazy Cat
                                $scoreArray[5] += 7;
                                break;
                            case 'Hide & Seek':
                                //Cuddly Cutie
                                $scoreArray[0] += 6;
                                //Timid Kitty
                                $scoreArray[1] += 6;
                                //Fluffy Fun
                                $scoreArray[2] += 6;
                                //Steady Sam
                                $scoreArray[3] += 7;
                                //Party Animal
                                $scoreArray[4] += 8;
                                //Crazy Cat
                                $scoreArray[5] += 8;
                                break;
                            case 'Twister':
                                //Cuddly Cutie
                                $scoreArray[0] += 6;
                                //Timid Kitty
                                $scoreArray[1] += 4;
                                //Fluffy Fun
                                $scoreArray[2] += 8;
                                //Steady Sam
                                $scoreArray[3] += 4;
                                //Party Animal
                                $scoreArray[4] += 10;
                                //Crazy Cat
                                $scoreArray[5] += 3;
                                break;
                            case 'Poker':
                                //Cuddly Cutie
                                $scoreArray[0] += 4;
                                //Timid Kitty
                                $scoreArray[1] += 9;
                                //Fluffy Fun
                                $scoreArray[2] += 6;
                                //Steady Sam
                                $scoreArray[3] += 4;
                                //Party Animal
                                $scoreArray[4] += 5;
                                //Crazy Cat
                                $scoreArray[5] += 5;
                                break;
                        }
                    }

                    //Question 1, What Work For Dogs
                    if (!empty($value['answers'][10]['choices'][0]['text']) && (key($petType) == 3)) {
                        switch ($value['answers'][10]['choices'][0]['text']) {
                            case 'Trades person':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 2;
                                //Cruiser
                                $scoreArray[2] += 2;
                                //Debonaire
                                $scoreArray[3] += 2;
                                //Defender
                                $scoreArray[4] += 8;
                                //Rough Nut
                                $scoreArray[5] += 10;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 7;
                                break;
                            case 'Detective or Spy':
                                //Aristocrat
                                $scoreArray[0] += 3;
                                //Buddy
                                $scoreArray[1] += 2;
                                //Cruiser
                                $scoreArray[2] += 4;
                                //Debonaire
                                $scoreArray[3] += 10;
                                //Defender
                                $scoreArray[4] += 7;
                                //Rough Nut
                                $scoreArray[5] += 2;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 5;
                                break;
                            case 'Personal Assistant':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 10;
                                //Cruiser
                                $scoreArray[2] += 2;
                                //Debonaire
                                $scoreArray[3] += 8;
                                //Defender
                                $scoreArray[4] += 2;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 3;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Bouncer':
                                //Aristocrat
                                $scoreArray[0] += 0;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 0;
                                //Debonaire
                                $scoreArray[3] += 7;
                                //Defender
                                $scoreArray[4] += 6;
                                //Rough Nut
                                $scoreArray[5] += 8;
                                //Twinkle Toes
                                $scoreArray[6] += 0;
                                //Wanderer
                                $scoreArray[7] += 10;
                                break;
                            case 'Mad Scientist':
                                //Aristocrat
                                $scoreArray[0] += 9;
                                //Buddy
                                $scoreArray[1] += 3;
                                //Cruiser
                                $scoreArray[2] += 4;
                                //Debonaire
                                $scoreArray[3] += 0;
                                //Defender
                                $scoreArray[4] += 0;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 6;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                            case 'Florist':
                                //Aristocrat
                                $scoreArray[0] += 5;
                                //Buddy
                                $scoreArray[1] += 4;
                                //Cruiser
                                $scoreArray[2] += 1;
                                //Debonaire
                                $scoreArray[3] += 5;
                                //Defender
                                $scoreArray[4] += 4;
                                //Rough Nut
                                $scoreArray[5] += 0;
                                //Twinkle Toes
                                $scoreArray[6] += 4;
                                //Wanderer
                                $scoreArray[7] += 0;
                                break;
                        }
                    }

                    //Question 1, Work For Cats
                    if (!empty($value['answers'][10]['choices'][0]['text']) && (key($petType) == 4)) {
                        switch ($value['answers'][10]['choices'][0]['text']) {
                            case 'Florist':
                                //Cuddly Cutie
                                $scoreArray[0] += 10;
                                //Timid Kitty
                                $scoreArray[1] += 3;
                                //Fluffy Fun
                                $scoreArray[2] += 7;
                                //Steady Sam
                                $scoreArray[3] += 3;
                                //Party Animal
                                $scoreArray[4] += 6;
                                //Crazy Cat
                                $scoreArray[5] += 3;
                                break;
                            case 'Detective or Spy':
                                //Cuddly Cutie
                                $scoreArray[0] += 0;
                                //Timid Kitty
                                $scoreArray[1] += 10;
                                //Fluffy Fun
                                $scoreArray[2] += 3;
                                //Steady Sam
                                $scoreArray[3] += 2;
                                //Party Animal
                                $scoreArray[4] += 3;
                                //Crazy Cat
                                $scoreArray[5] += 8;
                                break;
                            case 'Personal Assistant':
                                //Cuddly Cutie
                                $scoreArray[0] += 8;
                                //Timid Kitty
                                $scoreArray[1] += 2;
                                //Fluffy Fun
                                $scoreArray[2] += 10;
                                //Steady Sam
                                $scoreArray[3] += 4;
                                //Party Animal
                                $scoreArray[4] += 6;
                                //Crazy Cat
                                $scoreArray[5] += 0;
                                break;
                            case 'Tradie':
                                //Cuddly Cutie
                                $scoreArray[0] += 0;
                                //Timid Kitty
                                $scoreArray[1] += 1;
                                //Fluffy Fun
                                $scoreArray[2] += 3;
                                //Steady Sam
                                $scoreArray[3] += 8;
                                //Party Animal
                                $scoreArray[4] += 0;
                                //Crazy Cat
                                $scoreArray[5] += 2;
                                break;
                            case 'Door bitch':
                                //Cuddly Cutie
                                $scoreArray[0] += 4;
                                //Timid Kitty
                                $scoreArray[1] += 6;
                                //Fluffy Fun
                                $scoreArray[2] += 2;
                                //Steady Sam
                                $scoreArray[3] += 0;
                                //Party Animal
                                $scoreArray[4] += 8;
                                //Crazy Cat
                                $scoreArray[5] += 5;
                                break;
                            case 'Mad Scientist':
                                //Cuddly Cutie
                                $scoreArray[0] += 0;
                                //Timid Kitty
                                $scoreArray[1] += 9;
                                //Fluffy Fun
                                $scoreArray[2] += 0;
                                //Steady Sam
                                $scoreArray[3] += 0;
                                //Party Animal
                                $scoreArray[4] += 3;
                                //Crazy Cat
                                $scoreArray[5] += 10;
                                break;
                        }
                    }

                    foreach ($characterArray as $key => $linkedCharacter) {
                        // create new field collection entity for each value
                        $example_entity = NULL;
                        $example_entity = entity_create('field_collection_item', array('field_name' => 'field_pet_characters'));
                        // Attach the entity to the node
                        $example_entity->setHostEntity('node', $srNode);
                        // Wrap it
                        $wrapper = entity_metadata_wrapper('field_collection_item', $example_entity);
                        // Set the current value in the loop
                        $wrapper->field_linked_pet_character->set($linkedCharacter);
                        $wrapper->field_linked_character_score->set($scoreArray[$key]);
                        $wrapper->save();
                    }

                    // What are the top two?
                    asort($scoreArray);
                    $last = end($scoreArray);
                    $pNode->field_primary_pet_character[LANGUAGE_NONE][0]['target_id'] = $characterArray[key($scoreArray)];
                    //$pNode->field_primary_score[LANGUAGE_NONE][0]['value'] = $last;

                    $secondLast = prev($scoreArray);
                    // Save the references
                    $pNode->field_secondary_pet_character[LANGUAGE_NONE][0]['target_id'] = $characterArray[key($scoreArray)];
                    //$pNode->field_secondary_score[LANGUAGE_NONE][0]['value'] = $secondLast;

                    $total = $last + $secondLast;
                    $pNode->field_primary_score[LANGUAGE_NONE][0]['value'] = ceil(($last / $total) * 100);
                    $pNode->field_secondary_score[LANGUAGE_NONE][0]['value'] = floor(($secondLast / $total) * 100);

                    $pNode->field_owner[LANGUAGE_NONE][0]['target_id'] = $cNode->nid;

                    //Save pet
                    $pNode = node_submit($pNode); // Prepare node for a submit
                    node_save($pNode); // After this call we'll get a nid

                    //Save Pet Ref
                    $srNode->field_pet[LANGUAGE_NONE][0]['target_id'] = $pNode->nid;

                    watchdog('jpgf', 'New Pet created with ID %nid', array('nid' => $pNode->nid), WATCHDOG_NOTICE);

                    //Save SR
                    $srNode = node_submit($srNode); // Prepare node for a submit
                    node_save($srNode); // After this call we'll get a nid
                    watchdog('jpgf', 'New Survey Response created with ID %nid', array('nid' => $value['id']), WATCHDOG_NOTICE);
                    $petCharacters = array_merge(entity_load('node', array_values($pNode->field_primary_pet_character[LANGUAGE_NONE])), entity_load('node', array_values($pNode->field_secondary_pet_character[LANGUAGE_NONE])));
                    $petTypes = array();
                    $petDescriptions = array();
                    $petImages = array();
                    foreach ($petCharacters as $key => $character) {
                        $petTypes[] = $character->title;
                        $petDescriptions[] = $character->body[LANGUAGE_NONE][0]['safe_value'];
                        $petImages[] = $character->field_pet_image[LANGUAGE_NONE][0]['uri'];
                    }
                    $returnData[] = $value; // This can probably go?

                    $params = array(
                        'subject' => 'Congratulations ' . $cNode->title . '! Your ' . $pNode->title . ' is a ' . $petTypes[0] . '.',
                        'name' => $cNode->title,
                        'cID' => $cNode->nid,
                        'pID' => $pNode->nid,
                        'url' => url('node/' . $srNode->nid, array(
                            'absolute' => TRUE,
                            'alias' => FALSE
                        )),
                        'petName' => $pNode->title,
                        'petType' => $petTypes[0],
                        'petDescription' => $petDescriptions,
                        'petImage' => $petImages,
                        'pdf' => url('printpdf/' . $srNode->nid, array(
                            'absolute' => TRUE,
                            'alias' => FALSE
                        )),
                        'shareURL' => url(drupal_get_path_alias('node/' . $srNode->nid), array(
                            'absolute' => TRUE,
                            'alias' => FALSE
                        ))
                    );
                    $message = drupal_mail('jpgf', 'srprocesscomplete', $value['answers'][0]['form_fields'][4]['text'], LANGUAGE_NONE, $params);
                } else {
                    watchdog('jpgf', 'Node based on this Survey Response has already been created', NULL, WATCHDOG_NOTICE);
                }
            }
        }
        //TODO: This can go after testing?
        return $returnData;
    }
}

/**
 * Implements hook_page_build().
 *
 * Add JavaScript and CSS code to every page.
 */
function jpgf_page_build()
{
    drupal_add_css(drupal_get_path('module', 'jpgf') . '/css/jpgf.css');
}

function jpgf_cron()
{
    process_json();
}

function jpgf_mail($key, &$message, $params)
{
    $message['subject'] = t($params['subject']);
}